apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
  namespace: webapp
spec:
  selector:
    matchLabels:
      app: simple-webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      serviceAccountName: jenkins
      serviceAccount: jenkins
      containers:
        - name: simple-webapp
          image: docker.io/atwatanmalikm/webapp:2210150757
          ports:
            - containerPort: 80

